### ISSUE TITLE
Bad match on resource type

### ISSUE THREAD

**Issue by justinkillen** [thetalorian/klarify#4]
Resource type 'ServiceAccount' gets matched by 'Service'.

Example .klarify:

```
---
structure:
    "generated":
        - "."
categories:
    workload:
        - Service
    rbac:
        - ServiceAccount
```
